config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :students
  #get 'home/index'
  #root 'home#index'
  get 'home/about'
  root 'students#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :students



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about 
    @about_me = "My name is mike "
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  before_action :authenticate_user! , except: [:index, :show] 
  before_action :correct_user ,       only:   [:edit, :update , :destroy]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    #@student = Student.new
    @student= current_user.students.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    #@student = Student.new(student_params)
    @student= current_user.students.build(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  def correct_user
    @student = current_user.students.find_by(id: params[:id]) #lookup in the db 
    redirect_to student_path , notice: "Not authorized " if @student.nil?
  end


  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Osama webPage' , root_path ,class:"navbar-brand"   %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav navbar-dark  me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'About us' , home_about_path ,class:"nav-link"   %>       
      </li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Add student", new_student_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
           

   
      </ul>

    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About me ..</h1>
<p>
	<%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello Osama first webage</h1>
	My webage !

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
 
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <title>Osama webpage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class = "container">
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
      <br>
    <%= yield %> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
 <div class="field form-group">
    
    <%= form.number_field :user_id, id: :student_user_id, class:"form-control", placeholder:"User Id", type: :hidden ,value:current_user.id%>
  </div>
  <br/>
  <div class="field form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First name"%>
  </div>
<br/>
  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"last name"%>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :email , class:"form-control", placeholder:"Email"%>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :phone , class:"form-control", placeholder:"Phone"%>
  </div>
<br/>
  <div class="field form-group">

    <%= form.text_field :twitter, class:"form-control" , placeholder:"Twitter"%>
  </div>
  <br/>
  <div class="form-group">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>First name:</strong>
    <%= student.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= student.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= student.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= student.twitter %>
  </p>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student, class:"btn btn-secondary btn-sm" %> 
  <%= link_to "Back to students", students_path, class:"btn btn-secondary btn-dark btn-sm" %>
     <td><%= button_to 'Delete', @student, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger btn-sm"%></td>
</div>

app/views/students/index.html.erb
<% if user_signed_in? %>
<h1>Students</h1>

<table class="table ">
    <tr>
     <th > Name</th>
      <th >Email</th>
      <th >Phone</th>
      <th> Twitter </th>
      <th> User ID </th>


    </tr>
  </thead>
    <tbody>
        <% @students.each do |student| %>
        <% if student.user == current_user%> 

<tr>
      <td> <%= link_to student.first_name  + student.last_name   , student %> </td>      

      <td><%= student.email%></td>
      <td><%= student.phone %></td>
      <td><%= student.twitter %></td>
      <td><%= student.user_id %></td>

    
    <td><%= button_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger"%></td>


<%end%>
  <% end %>
  </tbody>
</table>

<%= link_to "New student", new_student_path, class:"btn btn-primary" %>
<% else %>
<h1>Hello Osama first webage</h1>
    My webage !
<%end%>

app/views/students/new.html.erb
<h1>Add New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path,class:"btn btn-secondary" %>
</div>

app/views/students/show.html.erb
<div class="card text-bg-light mb-3 text-center" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%@student.first_name %>     <%= @student.last_name %>
</h5>

  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%=@student.email%></li>
    <li class="list-group-item"><%=@student.phone%></li>
    <li class="list-group-item"><%=@student.twitter%></li>
  </ul>
 
 </div>
<div>
  <%= link_to "Edit this student", edit_student_path(@student) ,class:"btn btn-secondary "%> 
  <%= link_to "Back to students", students_path,class:"btn btn-secondary btn-dark" %>
 
</div>